### ISSUE TITLE
SE 2.3 Que es una transmisión serie o UART? Y que significan las siguientes propiedades: Baud Rate, Data Bits, Parity, Stop Bits, Send XON/XOFF, terminal Type.

### ISSUE THREAD

**Issue by Leytonale** [EMTSTISPC/Grupo10#12]

**Comment by estebancarrizo** [comment]
[TRANSMISION DE DATOS.pdf](https://github.com/EMTSTISPC/Grupo10/files/9413142/TRANSMISION.DE.DATOS.pdf)

**Comment by gonaiot** [comment]
@estebancarrizo 
Estimado Esteban, su trabajo puede ser mejorado. Recuerde que la documentacion ocupa un lugar importante en desarrollo. Aun asi participo en el flujo del repositorio, continue mejorando.
