### ISSUE TITLE
SE 1.1 Pedir el ingreso de dos números por terminal y mostrar la suma por la pantalla.

### ISSUE THREAD

**Issue by Leytonale** [EMTSTISPC/Grupo10#4]

**Comment by gonaiot** [comment]
@Leytonale 
Estimado Alejandro, su codigo funciona. Puede mejorarse. Recuerde la utilizacion de comentarios, a nivel de linea o bloque para detallarlo y a nivel general para explicar el algoritmo. Continue asi.
